{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Tabela 3\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.128.1380.0 (24.04)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "pt-BR",
    "cultures": [
      {
        "name": "pt-BR",
        "linguisticMetadata": {
          "content": {
            "Entities": {
              "tabela_3.nome": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Tabela 3",
                    "ConceptualProperty": "Nome"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Fornecedor": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "tabela_3.realizado": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Tabela 3",
                    "ConceptualProperty": "Realizado"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Data": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "tabela_3.responsáveis": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Tabela 3",
                    "ConceptualProperty": "Responsáveis"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Resp.": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              }
            },
            "Language": "en-US",
            "Version": "2.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "654114d2-2f05-4362-8c60-9bce44b2fb0b",
        "fromColumn": "Previsão",
        "fromTable": "Tabela 3",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_cda384b1-bf26-4c63-9303-2aea218e7b34"
      }
    ],
    "sourceQueryCulture": "pt-BR",
    "tables": [
      {
        "name": "DateTableTemplate_4eb08e5a-ce43-4779-8190-0c4e5d5708a8",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "cda79c5e-cb65-47cc-bbeb-4304c5267ad5",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "29ad6f02-9e75-45cc-9dfc-c5e4b7c6bdd7",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "ea43f628-e885-4b65-8895-0b0e19f57943",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "9f85084f-ff2f-45b1-9c86-2288d21e47ba",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "3ca2f7a5-ff68-428b-a193-0194cb4f92b0",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Trim \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "ae6829f0-ee3b-47b7-8fea-faf69230deee",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "9242dd2d-6de8-4bbc-bdd5-e5e79681817c",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarquia de datas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Ano",
                "column": "Ano",
                "lineageTag": "2fb5296b-780e-42f3-856b-882e0e8996e2",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "36ba892f-0eac-4f0f-b438-f1f8725ddee1",
                "ordinal": 1
              },
              {
                "name": "Mês",
                "column": "Mês",
                "lineageTag": "ad72e9d7-819d-47b0-b456-4aa1887eb43c",
                "ordinal": 2
              },
              {
                "name": "Dia",
                "column": "Dia",
                "lineageTag": "266e70cd-3b84-4ebe-9c4b-582bde1a5cb9",
                "ordinal": 3
              }
            ],
            "lineageTag": "459d9091-f81a-43b3-83a2-08d23cc2d2ad"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "3a5b84fe-ae26-43ee-ac0e-63b505950233",
        "partitions": [
          {
            "name": "DateTableTemplate_4eb08e5a-ce43-4779-8190-0c4e5d5708a8",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Tabela 3",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Responsáveis",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "761f6fe4-e16c-4634-9960-4c10db2fd234",
            "sourceColumn": "Responsáveis",
            "summarizeBy": "none"
          },
          {
            "name": "Nome",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "41688b4c-6d97-4f60-8483-1861ac7a08ad",
            "sourceColumn": "Nome",
            "summarizeBy": "none"
          },
          {
            "name": "Feedback da Versão",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8e94c24f-cab4-4a9d-89a8-948f9daa775d",
            "sourceColumn": "Feedback da Versão",
            "summarizeBy": "none"
          },
          {
            "name": "Realizado",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1a744db6-ef17-4874-bf42-191592ca4ddf",
            "sourceColumn": "Realizado",
            "summarizeBy": "none"
          },
          {
            "name": "Treinamento",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b6f4922e-c61b-4493-98d0-d37e4d10f95b",
            "sourceColumn": "Treinamento",
            "summarizeBy": "none"
          },
          {
            "name": "Cotação",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9d42710c-28c1-4bb7-90be-74f568f5a3b9",
            "sourceColumn": "Cotação",
            "summarizeBy": "none"
          },
          {
            "name": "Feedback da Cotação",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4067f7c0-eb33-41d0-a208-d167e703b255",
            "sourceColumn": "Feedback da Cotação",
            "summarizeBy": "none"
          },
          {
            "name": "Dispositivo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ac26498f-0a54-4190-b97e-892dbaf18bb2",
            "sourceColumn": "Dispositivo",
            "summarizeBy": "none"
          },
          {
            "name": "Previsão",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "a8bdbb40-542b-44f4-a10c-4799f5525207",
            "sourceColumn": "Previsão",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Hierarquia de datas",
                  "table": "LocalDateTable_cda384b1-bf26-4c63-9303-2aea218e7b34"
                },
                "isDefault": true,
                "relationship": "654114d2-2f05-4362-8c60-9bce44b2fb0b"
              }
            ]
          },
          {
            "name": "Horário agendado:",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "878608da-e887-45a4-b892-0d1ce70e08da",
            "sourceColumn": "Horário agendado:",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "8024a51b-ac36-4884-b1ac-48d9d4973a29",
        "partitions": [
          {
            "name": "Tabela 3",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Web.BrowserContents(\"https://docs.google.com/spreadsheets/d/e/2PACX-1vSPayUdromAe3saqOtPSMwdYWeKm7GnpZT74KjK3wivuI4BdsACxA9H5XJ6QrprIO5YSll_suQQUo4e/pubhtml\"),",
                "    #\"Tabela extraída de HTML\" = Html.Table(Fonte, {{\"Column1\", \"DIV:nth-child(3) > DIV.ritz.grid-container:nth-child(1) > TABLE.waffle.no-grid > * > TR > :nth-child(1)\"}, {\"Column2\", \"DIV:nth-child(3) > DIV.ritz.grid-container:nth-child(1) > TABLE.waffle.no-grid > * > TR > :nth-child(2)\"}, {\"Column3\", \"DIV:nth-child(3) > DIV.ritz.grid-container:nth-child(1) > TABLE.waffle.no-grid > * > TR > :nth-child(3)\"}, {\"Column4\", \"DIV:nth-child(3) > DIV.ritz.grid-container:nth-child(1) > TABLE.waffle.no-grid > * > TR > :nth-child(4)\"}, {\"Column5\", \"DIV:nth-child(3) > DIV.ritz.grid-container:nth-child(1) > TABLE.waffle.no-grid > * > TR > :nth-child(5)\"}, {\"Column6\", \"DIV:nth-child(3) > DIV.ritz.grid-container:nth-child(1) > TABLE.waffle.no-grid > * > TR > :nth-child(6)\"}, {\"Column7\", \"DIV:nth-child(3) > DIV.ritz.grid-container:nth-child(1) > TABLE.waffle.no-grid > * > TR > :nth-child(7)\"}, {\"Column8\", \"DIV:nth-child(3) > DIV.ritz.grid-container:nth-child(1) > TABLE.waffle.no-grid > * > TR > :nth-child(8)\"}, {\"Column9\", \"DIV:nth-child(3) > DIV.ritz.grid-container:nth-child(1) > TABLE.waffle.no-grid > * > TR > :nth-child(9)\"}, {\"Column10\", \"DIV:nth-child(3) > DIV.ritz.grid-container:nth-child(1) > TABLE.waffle.no-grid > * > TR > :nth-child(10)\"}, {\"Column11\", \"DIV:nth-child(3) > DIV.ritz.grid-container:nth-child(1) > TABLE.waffle.no-grid > * > TR > :nth-child(11)\"}, {\"Column12\", \"DIV:nth-child(3) > DIV.ritz.grid-container:nth-child(1) > TABLE.waffle.no-grid > * > TR > :nth-child(12)\"}, {\"Column13\", \"DIV:nth-child(3) > DIV.ritz.grid-container:nth-child(1) > TABLE.waffle.no-grid > * > TR > :nth-child(13)\"}, {\"Column14\", \"DIV:nth-child(3) > DIV.ritz.grid-container:nth-child(1) > TABLE.waffle.no-grid > * > TR > :nth-child(14)\"}, {\"Column15\", \"DIV:nth-child(3) > DIV.ritz.grid-container:nth-child(1) > TABLE.waffle.no-grid > * > TR > :nth-child(15)\"}, {\"Column16\", \"DIV:nth-child(3) > DIV.ritz.grid-container:nth-child(1) > TABLE.waffle.no-grid > * > TR > :nth-child(16)\"}, {\"Column17\", \"DIV:nth-child(3) > DIV.ritz.grid-container:nth-child(1) > TABLE.waffle.no-grid > * > TR > :nth-child(17)\"}, {\"Column18\", \"DIV:nth-child(3) > DIV.ritz.grid-container:nth-child(1) > TABLE.waffle.no-grid > * > TR > :nth-child(18)\"}, {\"Column19\", \"DIV:nth-child(3) > DIV.ritz.grid-container:nth-child(1) > TABLE.waffle.no-grid > * > TR > :nth-child(19)\"}, {\"Column20\", \"DIV:nth-child(3) > DIV.ritz.grid-container:nth-child(1) > TABLE.waffle.no-grid > * > TR > :nth-child(20)\"}, {\"Column21\", \"DIV:nth-child(3) > DIV.ritz.grid-container:nth-child(1) > TABLE.waffle.no-grid > * > TR > :nth-child(21)\"}, {\"Column22\", \"DIV:nth-child(3) > DIV.ritz.grid-container:nth-child(1) > TABLE.waffle.no-grid > * > TR > :nth-child(22)\"}, {\"Column23\", \"DIV:nth-child(3) > DIV.ritz.grid-container:nth-child(1) > TABLE.waffle.no-grid > * > TR > :nth-child(23)\"}, {\"Column24\", \"DIV:nth-child(3) > DIV.ritz.grid-container:nth-child(1) > TABLE.waffle.no-grid > * > TR > :nth-child(24)\"}, {\"Column25\", \"DIV:nth-child(3) > DIV.ritz.grid-container:nth-child(1) > TABLE.waffle.no-grid > * > TR > :nth-child(25)\"}, {\"Column26\", \"DIV:nth-child(3) > DIV.ritz.grid-container:nth-child(1) > TABLE.waffle.no-grid > * > TR > :nth-child(26)\"}, {\"Column27\", \"DIV:nth-child(3) > DIV.ritz.grid-container:nth-child(1) > TABLE.waffle.no-grid > * > TR > :nth-child(27)\"}, {\"Column28\", \"DIV:nth-child(3) > DIV.ritz.grid-container:nth-child(1) > TABLE.waffle.no-grid > * > TR > :nth-child(28)\"}, {\"Column29\", \"DIV:nth-child(3) > DIV.ritz.grid-container:nth-child(1) > TABLE.waffle.no-grid > * > TR > :nth-child(29)\"}}, [RowSelector=\"DIV:nth-child(3) > DIV.ritz.grid-container:nth-child(1) > TABLE.waffle.no-grid > * > TR\"]),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"Tabela extraída de HTML\",{{\"Column1\", Int64.Type}, {\"Column2\", type text}, {\"Column3\", type text}, {\"Column4\", type text}, {\"Column5\", type text}, {\"Column6\", type text}, {\"Column7\", type text}, {\"Column8\", type text}, {\"Column9\", type text}, {\"Column10\", type text}, {\"Column11\", type text}, {\"Column12\", type text}, {\"Column13\", type text}, {\"Column14\", type text}, {\"Column15\", type text}, {\"Column16\", type text}, {\"Column17\", type text}, {\"Column18\", type text}, {\"Column19\", type text}, {\"Column20\", type text}, {\"Column21\", type text}, {\"Column22\", type text}, {\"Column23\", type text}, {\"Column24\", type text}, {\"Column25\", type text}, {\"Column26\", type text}, {\"Column27\", type text}, {\"Column28\", type text}, {\"Column29\", type text}}),",
                "    #\"Colunas Removidas\" = Table.RemoveColumns(#\"Tipo Alterado\",{\"Column1\"}),",
                "    #\"Linhas Superiores Removidas\" = Table.Skip(#\"Colunas Removidas\",1),",
                "    #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(#\"Linhas Superiores Removidas\", [PromoteAllScalars=true]),",
                "    #\"Tipo Alterado1\" = Table.TransformColumnTypes(#\"Cabeçalhos Promovidos\",{{\"Responsáveis\", type text}, {\"Nome\", type text}, {\"Feedback da Versão\", type text}, {\"Realizado\", type text}, {\"Treinamento\", type text}, {\"Cotação\", type text}, {\"Feedback da Cotação\", type text}, {\"Dispositivo\", type text}, {\"\", type text}, {\"Previsão\", type date}, {\"_1\", type text}, {\"Horário agendado:\", type text}, {\"_2\", type text}, {\"_3\", type text}, {\"_4\", type text}, {\"_5\", type text}, {\"_6\", type text}, {\"_7\", type text}, {\"_8\", type text}, {\"_9\", type text}, {\"_10\", type text}, {\"_11\", type text}, {\"_12\", type text}, {\"_13\", type text}, {\"_14\", type text}, {\"_15\", type text}, {\"_16\", type text}, {\"_17\", type text}}),",
                "    #\"Colunas Removidas1\" = Table.RemoveColumns(#\"Tipo Alterado1\",{\"\", \"_1\", \"_2\", \"_3\", \"_4\", \"_5\", \"_6\", \"_7\", \"_8\", \"_9\", \"_10\", \"_11\", \"_12\", \"_13\", \"_14\", \"_15\", \"_16\", \"_17\"}),",
                "    #\"Linhas em Branco Removidas\" = Table.SelectRows(#\"Colunas Removidas1\", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {\"\", null})))",
                "in",
                "    #\"Linhas em Branco Removidas\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_cda384b1-bf26-4c63-9303-2aea218e7b34",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "5a4a06d7-f85e-4db4-a08d-53883958baab",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "fffab876-5cf2-4b88-9aa3-5cd8d410997c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "d3f8cbdf-c277-41b6-9dfc-cbb21114141b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "4bc42ba7-24a5-4e72-9d9a-26722cbeef52",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "9268e4d1-018e-41d1-b240-675332aaab30",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Trim \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "9921415d-0b93-41e0-9e04-8e43b5019984",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "27519245-86d8-48ac-8d7e-0c150db047b5",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarquia de datas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Ano",
                "column": "Ano",
                "lineageTag": "cfef4c6a-40e3-40ae-a476-b76c6e276e17",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "3f589aac-6437-4275-9fb3-a758d6c354e1",
                "ordinal": 1
              },
              {
                "name": "Mês",
                "column": "Mês",
                "lineageTag": "5d5f9d4f-5a3f-42a5-9f6c-fee911f144e1",
                "ordinal": 2
              },
              {
                "name": "Dia",
                "column": "Dia",
                "lineageTag": "f180c7f0-99b6-4e3b-9016-4d14a33b8197",
                "ordinal": 3
              }
            ],
            "lineageTag": "56ff982b-5ab6-46cd-9a25-a13b5193efa3"
          }
        ],
        "isHidden": true,
        "lineageTag": "ead4f55b-2eae-435b-b349-42bf286ac6af",
        "partitions": [
          {
            "name": "LocalDateTable_cda384b1-bf26-4c63-9303-2aea218e7b34",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Tabela 3'[Previsão])), 1, 1), Date(Year(MAX('Tabela 3'[Previsão])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      }
    ]
  }
}